name = "ReSHOP_jll"
uuid = "b1e335f6-4372-40fd-9431-5a5c4704c04b"
authors = ["Olivier Huber <oli.huber@gmail.com>"]
version = "0.1.2"
repo = "https://github.com/xhub/ReSHOP_jll.jl.git"
desc = "Binaries for the ReSHOP library"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"
